<Project Sdk="Microsoft.NET.Sdk.Worker">
  <Import Project="..\..\Directory.Build.props" />
  <ItemGroup>
    <ProjectReference Include="..\EkbReviews.Application\EkbReviews.Application.csproj" />
    <ProjectReference Include="..\EkbReviews.Infrastructure\EkbReviews.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.9" />
  </ItemGroup>
</Project>
